# Generated by Django 5.1 on 2024-08-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
