# Generated by Django 5.1 on 2024-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0016_alter_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], max_length=20, null=True),
        ),
    ]
